"Syntax Highlighting
if has("syntax")
    syntax on
endif

set autoindent
set cindent
set nu

set tabstop=2
set shiftwidth=2

au BufReadPost *
\ if line("'\"") > 0 && line("'\"") <= line("$") |
\ exe "norm g`\"" |
\ endif

set laststatus=2 
set statusline=\ %<%l:%v\ [%P]%=%a\ %h%m%r\ %F\

set hlsearch
set expandtab

set ruler

au BufNewFile,BufRead *.sv,*.svh,*.vh,*.v so ~/.vim/syntax/verilog_systemverilog.vim

set title
set wmnu
set bs=indent,eol,start
